service: coldstart-node
frameworkVersion: '~4.0'

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  memorySize: 1024
  timeout: 5
  profile: awsDevelopment
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /node/hello
          method: GET
