service: coldstart-python
frameworkVersion: '~4.0'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.11
  architecture: arm64
  memorySize: 1024
  timeout: 5
  profile: awsDevelopment
  stage: dev
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    noDeps: false
    zip: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /python/hello
          method: GET
